[package]
name = "verify-kat"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
sha3 = "0.10"
hkdf = "0.12"
aes-gcm = "0.10"
aes-gcm-siv = "0.11"
aead = "0.5"
anyhow = "1"
