name: Release to crates.io

on:
  push:
    tags: ["v*"]

permissions:
  id-token: write    # OIDC for trusted publishing
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Show workspace crates
        run: cargo metadata --no-deps -q | jq -r '.packages[] | .name + "  " + .manifest_path'

      - name: Run tests
        run: cargo test --all-features --workspace

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-features --workspace -- -D warnings

      - name: Dry run packaging
        run: |
          cargo package -p qsfs-core --no-verify
          cargo package -p qsfs --no-verify

      - name: Publish qsfs-core to crates.io
        run: cargo publish -p qsfs-core --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Wait for crates.io index update
        run: sleep 60

      - name: Publish qsfs CLI to crates.io
        run: cargo publish -p qsfs --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/package/qsfs-core-*.crate
            target/package/qsfs-*.crate
